site_name: Tikz-Python 
theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/ltrujello/Tikz-Python


